### ISSUE TITLE
feat: user-registration

### ISSUE THREAD

**Issue by maskedman0** [maskedman0/modulearn-be#3]
## 📝 Description
Create a route where you can enable publishers to register an account.

### MODEL SCHEMA
```typescript
{
    firstName: string; // required
    lastName: string; // required
    userType: string; // auto-assigned
    email: string; // required
    gender: string; // optional
    birthDate: string; // optional
    fullAddress: string; // optional
    mobile: string; // optional
    phone: string // optional
}
```

### REQUEST BODY
```typescript
{
    firstName: string;
    lastName: string;
    userType: string;
    email: string;
    gender: string;
    birthDate: string;
    fullAddress: string;
    mobile: string;
    phone: string
}
```

### SUCCESS RESPONSE
```typescript
{
   statusCode: 201,
   message: "Registration successful!",
   data: {
        firstName: string,
        lastName: string,
        userType: string,
        email: string,
        gender: string,
        birthDate: string,
        fullAddress: string,
        mobile: string,
        phone: string,
   }
}
```

### VALIDATION ERROR RESPONSE
```typescript
{
   statusCode: 422,
   message: "Invalid registration",
   data:  {
        errors: [
             ...errors
        ]
   }
}
```

## ⚙️ Module
user module

## 📋 Todo:
- [x] create user-model
- [x] create user-interface
- [ ] create user-registration service
- [ ] create user-registration route handler
